[package]
name = "penpenic_times_table"
version = "3.0.0-alpha.1"
edition = "2021"

[dependencies]
yew = "0.19.*"
serde = "1.0.*"
serde_json = "1.0.*"
web-sys = {version = "0.3.57", features = ["HtmlInputElement"]}
gloo-console = "0.2.1"
gloo-storage = "0.2.1"